from typing import TypedDict, List, Optional, Literal
from pydantic import BaseModel, Field

class Hint(BaseModel):
    """Structured output for the Socratic hint."""
    analysis: str = Field(description="A concise analysis of the user's error, e.g., 'Off-by-one error in binary search' or 'Time complexity is O(N^2)'.")
    counter_example_input: str = Field(description="The specific counter-example generated by the Hacker node that breaks the user's code.")
    socratic_hint: str = Field(description="The actual Socratic hint given to the user. Must be non-spoiler and guide their thinking.")
    complexity_advice: Optional[str] = Field(description="Advice regarding the algorithmic complexity, if applicable (e.g., 'Consider an O(N log N) approach').")

# --- Graph State Definition ---
class GraphState(TypedDict):
    """
    Represents the state of our graph.
    The keys are the names of the variables, and the values are the types.
    """
    problem_url: str
    user_code: str
    language: Literal["C++", "Python", "Java"]
    
    # RAG/Ingestion Output
    problem_context: str
    
    # Hacker/Test Generator Output
    generated_test_case: str
    
    # Code Execution/Analysis Output
    execution_status: Literal["PASS", "FAIL", "ERROR"]
    execution_output: str # stdout/stderr or simplified error message
    
    # Tutor/Critic Output
    current_hint: Optional[Hint]
    reflection_count: int
    feedback: Optional[str] # Used by the Critic node to give feedback to the Tutor
    
    # Final Output
    final_response: Optional[str]